api/urls.py
from django.urls import path
from . import views


# SET THE NAMESPACE!
app_name = 'api'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('face/recognition',views.verify_face_recognition,name='verify_face_recognition'),
    path('object/detection',views.Object_Detection,name='object_detection')
]

project/urls.py
from django.contrib import admin
from django.urls import path
from api import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('special/', views.special, name='special'),
    path('api/', include('api.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('detail/',views.detail,name='detail'),
    path('my_account/',views.my_account,name='my_account'),
    path('my_fridge/',views.My_Fridge,name='My_Fridge'),
    path('recipe_detail/<int:pk>/',views.Recipe_detail,name="recipe_detail"),
    path('recommandation/',views.Recommandation,name='recommandation')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models
from jsonfield import JSONField
from django.template.defaultfilters import slugify
from .face_encoding import FaceEncoding
from django.contrib.auth.models import User
from django.utils import timezone
import json
# Create your models here.

#upload folder
upload_Memberfolder = 'image/'
upload_Recipefolder = 'recipe/'
#define rename function
def photo_path(instance, filename):
    basefilename, file_extension= os.path.splitext(filename)
    return 'images/{basename}{ext}'.format(basename= instance.user.id,ext= file_extension)
#create Member
class Member(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    locale = models.CharField(max_length=10)
    slug = models.SlugField(max_length=200,unique=True,editable=False)
    avatar_encoding = JSONField(editable=False)
    # created_at = models.DateTimeField(editable=False)
    # updated_at = models.DateTimeField(editable=False)
    image_url = models.ImageField(upload_to=upload_Memberfolder,blank=True)
    def save(self,*args,**kwargs):
        """On save"""
        # create unique slug with name and id
        new = self.user.username+str(self.user.id)
        self.slug = slugify(new)
        self.avatar_encoding = FaceEncoding(self.image_url)
        # new_name= upload_folder+self.name+"."+str(self.image_url).split('.')[-1]
        # self.image_url =new_name
        return super(Member,self).save(*args,**kwargs)
    def __str__(self):
        return self.slug


class Recipe(models.Model):
    id=models.BigIntegerField(primary_key=True)
    name=models.CharField(max_length=200)
    description=models.CharField(max_length=200,null=True)
    img_url=models.ImageField(upload_to=upload_Recipefolder,null=True)
    cooking_time=models.CharField(max_length=20,null=True)
    ingredient_table=JSONField(null=True)
    cooking_steps=JSONField(null=True)
    def __str__(self):
        return self.name

class Food_Category(models.Model):
    id=models.BigAutoField(primary_key=True)
    food_name=models.CharField(max_length=200)
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField(editable=False)
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(Food_Category, self).save(*args, **kwargs)
    def __str__(self):
        return self.food_name

class Member_Fridge(models.Model):
    id = models.BigAutoField(primary_key=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    food_category=models.ForeignKey(Food_Category,on_delete=models.CASCADE)
    food_qty=models.IntegerField()
    fridge_img_url=models.CharField(max_length=120)
    fridge_predict_img_url = models.CharField(max_length=120)
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField(editable=False)
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(Member_Fridge, self).save(*args, **kwargs)
    def __str__(self):
        return self.user

api/forms.py
from django import forms
from api.models import Member
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','first_name','last_name','password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = Member
        fields = ('locale', 'image_url')

api/views.py
import os
import uuid
import json
import numpy as np
from django.shortcuts import render
from api.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from api.models import Member,Food_Category,Member_Fridge,Recipe
from django.http import JsonResponse
from core.image import (convert_and_save, create_dir_folder, getBase64Str,
                          is_base64_image)

from yolo.predict import _main_
from django.views.decorators.csrf import csrf_exempt
import numpy as np
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from .face_encoding import detect_faces_in_image
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
####set up parameter####
media_root=settings.MEDIA_ROOT
config_path=settings.BASE_DIR+'/config.json'
ori_dirname=media_root+'/base64/'
yolo_output_path=media_root+'/yolo/'
########################



def index(request):
    return render(request,'api/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            # if 'image_url' in request.FILES:
            #     print('found it')
            profile.image_url = request.FILES.get('image_url')
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'api/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'api/login.html', {})
@login_required()
def detail(request):
    list_detail = Member.objects.filter(user=request.user)  # 把資料庫中對應user的資料全部撈出來
    context ={"list_detail":list_detail}
    return render(request, 'upload_profile/detail.html', context)

@login_required()
def my_account(request):
    account = Member.objects.filter(user_id=request.user.id).first()
    context = {"account": account}
    return render(request, 'my_account.html', context)

@login_required()
def My_Fridge(request):
    data = Member_Fridge.objects.filter(user=request.user.id)#.values('food_qty')
    jsondata ={}
    food_list = []

    for item in data:
        food_list.append({"id":item.food_category.id,"food_name":item.food_category.food_name,
                          "fridge_predict_img_url": item.fridge_predict_img_url,
                                   "food_qty":item.food_qty,"created_at":item.created_at,"updated_at":item.updated_at})
    jsondata['foods']=food_list
    return render(request, 'fridge.html', jsondata)

@login_required()
def Recommandation(request):
    data = Member_Fridge.objects.filter(user=request.user.id)  # .values('food_qty')
    food_list = []
    mapping={"milk":"牛奶","guava":"芭樂","cabbage":"高麗菜"}
    for item in data:
        food_list.append(mapping[item.food_category.food_name])
    data_r = Recipe.objects.all()
    recipe_dict={}
    for item in data_r:
        ingred = item.ingredient_table
        recipe_dict[item.id]=''.join(ingred)

    recommand_id = []
    for food in food_list:
        for k,v in recipe_dict.items():
            if food in v:
                recommand_id.append(k)
    recommand_id=list(set(recommand_id))
    recommand=[]

    for rid in recommand_id:
        a=Recipe.objects.filter(pk=rid)
        for i in a:
            recommand.append({"id":i.id,"name":json.loads(json.dumps(i.name)),"description":json.loads(json.dumps(i.description))})
    jsondata={}
    jsondata['recommand']=recommand
    return render(request, 'recommand.html', jsondata)
    # return HttpResponse('shit')
def Recipe_detail(request,pk):
    data =Recipe.objects.filter(pk=pk)
    jsondata = {}
    recipe_detail = []
    for item in data:
        recipe_detail.append({"id":item.id,"name":item.name,
                              "description": item.description,
                              "img_url":item.img_url,"cooking_time":item.cooking_time,
                              "ingredient_table":json.loads(json.dumps(item.ingredient_table)),
                              "cooking_steps": json.loads(json.dumps(item.cooking_steps))})
    jsondata['recipe_detail'] = recipe_detail
    return render(request,'recipe_detail.html',jsondata)


@api_view(['POST'])
def verify_face_recognition(request):
    if request.method == 'POST':
        data = request.data

        if is_base64_image(data['file']):
            b64_string = getBase64Str(data['file'])
        else:
            return Response({"error": "base64 image format is not correct"}, status=status.HTTP_400_BAD_REQUEST)

        dirname = 'media/face_recognition/'
        filename = str(uuid.uuid1())

        if not os.path.exists(dirname):
            create_dir_folder(dirname)

        try:
            members = Member.objects.values("slug", "user_id", "avatar_encoding")
        except Member.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        # Get face encodings for any faces in the uploaded image
        unknown_face_img = convert_and_save(b64_string, dirname, filename)

        known_face_encoding = []
        known_faces = []
        known_face_names = []
        user_ids = []

        for member in members:
            known_face_encoding.append(np.array(json.loads(member['avatar_encoding'])))
            known_face_names.append(member['slug'])
            user_ids.append(member['user_id'])

        result = detect_faces_in_image(unknown_face_img, known_face_encoding, known_face_names, user_ids)

        return Response(result)


@api_view(['POST'])
def Object_Detection(request):
    if request.method == "POST":
        data = request.data

        id = int(data['user_id'])
        #save origin base64 and predicted image
        file = data['file']
        if is_base64_image(file):
            b64_string = getBase64Str(file)
        else:
            return JsonResponse({"error": "base64 image format is not correct"})

        if not os.path.exists(ori_dirname):
            create_dir_folder(ori_dirname)
        username = User.objects.get(id=id).username
        img_ori = convert_and_save(b64_string,ori_dirname, username)

        label_result, fridge_predict_img_url= _main_(config_path=config_path,input_path=img_ori,output_path=yolo_output_path)

        # calculate total inventory of in DB
        inventory = Member_Fridge.objects.all()
        inventories = {}
        for invent in inventory:
            # print(invent.food_category,type(invent.food_category),invent.food_category.id,type(invent.food_category.id))
            food_name = str(invent.food_category)
            if food_name not in inventories.keys():
                inventories[food_name] = int(invent.food_qty)
            else:
                inventories[food_name] += int(invent.food_qty)

        # calculate difference between inventories and label_result
        # part1: calculate food "vanished"
        diff={}
        for k in inventories.keys():
            if k not in label_result.keys():
                diff[k]=-1*int(inventories[k])
        #         food_category = Food_Category.objects.get(food_name=k)
        #         Member_Fridge.objects.filter(food_category=food_category,user=id).delete()
        #
        # part2: calculate diff of food still "existed"
        for k in label_result.keys():
            if k in inventories.keys():
                diff[k]=label_result[k]-inventories[k]
            else:
                diff[k]=label_result[k]
        # calculate updated inventory of in DB under corresponding "id"
        p_inventory = Member_Fridge.objects.filter(user=id)
        p_inventories = {}
        for invent in p_inventory:
            food_name = str(invent.food_category)
            if food_name not in p_inventories.keys():
                p_inventories[food_name] = int(invent.food_qty)
            else:
                p_inventories[food_name] += int(invent.food_qty)

        p_updates={}
        for k in diff.keys():
            if k in p_inventories.keys():
                p_updates[k]=diff[k]+p_inventories[k]
            else:
                p_updates[k]=diff[k]

        # update new inventory into db_Member_Fridge of under corresponding "id"
        for k in p_updates.keys():
            if k in p_inventories.keys():
                food_qty = int(p_updates[k])
                food_category = Food_Category.objects.get(food_name=k)

templates/api/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">IFridge</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <!--<li class="nav-item">-->
            <!--<a class="nav-link" href="{% url 'admin:index' %}">Admin</a>-->
          <!--</li>-->
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'my_account' %}">My Account</a></li>
            <!--<li class="nav-item"><a class="nav-link" href="{% url 'detail' %}">Account</a></li>-->
            <li class="nav-item"><a class="nav-link" href="{% url 'My_Fridge' %}">My Fridge</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'recommandation' %}">Recommandation</a></li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'api:register' %}">Register</a>
            </li>
            <li class="nav-item"><a class="nav-link" class="nav-link" href="{% url 'api:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container-flud">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/api/index.html
{% extends "api/base.html" %}
{% block body_block %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">IFridge</h1>
    <p class="lead">Start your Smart Refrigerator!</p>
  </div>
</div>

<div class="container mb-5">
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <p>
            Check out your food now.
            <a class="btn btn-warning btn-xm" href="{% url 'My_Fridge' %}">My fridge</a>
        </p>
    {% else %}
    <p class="mb-5">
        <a class="btn btn-warning btn-lg btn-block" href="{% url 'api:user_login' %}">Log in</a>
    </p>
    <p>
        Don't have an account?
        <a class="btn btn-outline-warning btn-lg btn-block" href="{% url 'api:register' %}">Sign up</a>
    </p>
    {% endif %}
</div>
{% endblock %}

templates/api/login.html
{% extends 'api/base.html' %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Log In</h1>
    <p class="lead">Nice to see you again!</p>
  </div>
</div>

<div class="container">
  <form method="post" action="{% url 'api:user_login' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username</label>
        <input name="username" type="text" class="form-control" id="username" placeholder="Username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input name="password" type="password" class="form-control" id="password" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-warning">Log In</button>
 </form>
</div>
{% endblock %}

templates/api/registration.html
{% extends 'api/base.html' %}
{% load staticfiles %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Sign Up</h1>
    <p class="lead">Nice to meet you!</p>
  </div>
</div>

<div class="container">
    {% csrf_token %}
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Just fill out the form.</h3>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}